name: TOTP Generator
description: This action generates auth codes for use in actions.
author: Khai Nguyen Nguyen
branding:
  icon: hash
  color: yellow
inputs:
  totp_key:
    description: Used to generate 2FA codes.
    required: true
outputs:
  code:
    description: Generated auth code.
runs:
  using: node16
  main: dist/index.js
